name: spaktok_frontend
description: "Spaktok Flutter Web app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.1.1
  firebase_core_web: ^3.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  flutter_webrtc: ^1.2.0
  permission_handler: ^12.0.1
  lottie: ^3.3.2
  camera: ^0.11.3
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_selfie_segmentation: ^0.10.0
  google_mlkit_text_recognition: ^0.14.0
  google_mlkit_language_id: ^0.13.0
  image: ^4.1.3
  path_provider: ^2.1.1
  agora_rtc_engine: ^6.3.2
  video_player: ^2.8.1
  chewie: ^1.7.5
  audioplayers: ^6.5.1
  google_mlkit_translation: ^0.13.0
  google_mlkit_smart_reply: ^0.13.0
  record: ^6.1.2
  just_audio: ^0.10.5
  file_picker: ^10.3.3
  emoji_picker_flutter: ^4.3.0
  uuid: ^4.2.1
  web_socket_channel: ^2.4.0
  http: ^1.2.1
  socket_io_client: ^2.0.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
