name: spaktok
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
<<<<<<< HEAD
  sdk: ">=3.3.0 <4.0.0"
=======
  sdk: "3.35.5"
>>>>>>> feature/full-implementation

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
<<<<<<< HEAD
  firebase_core: ^4.1.1
  firebase_core_web: ^3.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  flutter_webrtc: ^1.2.0
  permission_handler: ^12.0.1
  lottie: ^3.3.2 # For animated Lottie components
  camera: ^0.11.2 # Camera functionality
  google_mlkit_face_detection: ^0.13.1 # Face detection and landmarks
  google_mlkit_selfie_segmentation: ^0.10.0 # Background removal/green screen
  image: ^4.1.3 # Image processing
  path_provider: ^2.1.1 # File path management
  agora_rtc_engine: ^6.3.2 # Agora RTC for live streaming
  video_player: ^2.8.1 # Video playback for reels
  chewie: ^1.7.5 # Video player UI
  audioplayers: ^6.5.1 # Audio playback
  google_mlkit_translation: ^0.13.0 # On-device translation
  google_mlkit_smart_reply: ^0.13.0 # Smart reply suggestions
  record: ^6.1.2 # Audio recording for voice messages
  just_audio: ^0.10.5 # Advanced audio playback
  file_picker: ^10.3.3 # File selection for media
  emoji_picker_flutter: ^4.3.0 # Emoji picker
  uuid: ^4.2.1 # Unique IDs for messages
=======
  video_player: ^2.8.1
  web_socket_channel: ^2.4.0
>>>>>>> feature/full-implementation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8


flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700

<<<<<<< HEAD
=======
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  firebase_core: ^2.24.2


  firebase_core_web: ^3.1.1



  cloud_firestore: ^4.13.6

>>>>>>> feature/full-implementation
