version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "5003:5000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  firebase:
    build: ./firebase
    ports:
      - "4000:4000"
      - "5001:5001"
      - "5003:5000"
      - "8080:8080"
      - "9099:9099"
      - "9199:9199"
    volumes:
      - ./firebase:/firebase
    restart: unless-stopped
