version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: spaktok-frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: spaktok-backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CORS_ORIGIN: "*"
      # Optional Firebase settings (use env or ADC in prod)
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET:-}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL:-}
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: spaktok-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    container_name: spaktok-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:15
    container_name: spaktok-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: spaktok
      POSTGRES_PASSWORD: 123dano
      POSTGRES_DB: spaktok
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  mongo-data:
  pg_data:
