version: "3.9"

services:
  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    volumes:
      - ./frontend:/app
      - /app/build
    command: flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0 --dart-define=DEBUG=true
