name: spaktok
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^4.1.1
  agora_rtc_engine: ^6.5.3
<<<<<<< HEAD
  permission_handler: ^12.0.1
=======
  permission_handler: ^10.4.5
>>>>>>> origin/cursor/send-arabic-greeting-070f
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  flutter_stripe: ^12.0.2
  firebase_storage: ^13.0.2
  camera: ^0.11.0+1
  image_picker: ^1.0.7
  provider: ^6.1.2
  image: ^4.0.17
  photo_view: ^0.15.0
  flutter_colorpicker: ^1.0.3
  path_provider: ^2.1.1
  video_player: ^2.8.1
  chewie: ^1.7.4
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
<<<<<<< HEAD
  flutter_screenshot_detect: ^0.1.7
  cloud_functions: ^6.0.2
  geolocator: ^14.0.2
=======
  google_maps_flutter: ^2.5.0
  ar_flutter_plugin: ^0.7.3
  share_plus: ^7.0.2
>>>>>>> origin/cursor/send-arabic-greeting-070f

dev_dependencies:
  flutter_test:
    sdk: flutter

<<<<<<< HEAD
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
=======
  flutter_lints: ^4.0.0
>>>>>>> origin/cursor/send-arabic-greeting-070f
  mockito: ^5.4.4

flutter:
  generate: true
  uses-material-design: true

<<<<<<< HEAD
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

=======
>>>>>>> origin/cursor/send-arabic-greeting-070f
