name: spaktok
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^4.1.1
  agora_rtc_engine: ^6.5.3
  permission_handler: ^10.4.5
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  flutter_stripe: ^11.5.0
  firebase_storage: ^13.0.2
  camera: ^0.11.0+1
  image_picker: ^1.0.7
  provider: ^6.1.2
  image: ^4.0.17
  photo_view: ^0.14.0
  flutter_colorpicker: ^1.0.3
  path_provider: ^2.1.1
  video_player: ^2.8.1
  chewie: ^1.7.4
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  ar_flutter_plugin: ^0.7.3
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mockito: ^5.4.4

flutter:
  generate: true
  uses-material-design: true

