import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:spaktok/services/auth_service.dart';
import 'dart:io';

/// Memory Category
enum MemoryCategory {
  favorites,
  friends,
  travel,
  food,
  selfies,
  pets,
  events,
  daily,
  other,
}

/// Memory Model
class Memory {
  final String id;
  final String userId;
  final String contentId;
  final String contentType; // 'story', 'video', 'photo'
  final String mediaUrl;
  final String? thumbnailUrl;
  final MemoryCategory category;
  final List<String> tags;
  final String? caption;
  final DateTime originalDate;
  final DateTime savedAt;
  final bool isFavorite;
  final Map<String, dynamic>? location;
  final List<String>? peopleTagged;

  Memory({
    required this.id,
    required this.userId,
    required this.contentId,
    required this.contentType,
    required this.mediaUrl,
    this.thumbnailUrl,
    required this.category,
    required this.tags,
    this.caption,
    required this.originalDate,
    required this.savedAt,
    this.isFavorite = false,
    this.location,
    this.peopleTagged,
  });

  factory Memory.fromMap(Map<String, dynamic> map, String id) {
    return Memory(
      id: id,
      userId: map['userId'] ?? '',
      contentId: map['contentId'] ?? '',
      contentType: map['contentType'] ?? '',
      mediaUrl: map['mediaUrl'] ?? '',
      thumbnailUrl: map['thumbnailUrl'],
      category: MemoryCategory.values.firstWhere(
        (e) => e.toString().split('.').last == map['category'],
        orElse: () => MemoryCategory.other,
      ),
      tags: List<String>.from(map['tags'] ?? []),
      caption: map['caption'],
      originalDate: (map['originalDate'] as Timestamp).toDate(),
      savedAt: (map['savedAt'] as Timestamp).toDate(),
      isFavorite: map['isFavorite'] ?? false,
      location: map['location'],
      peopleTagged: map['peopleTagged'] != null
          ? List<String>.from(map['peopleTagged'])
          : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'userId': userId,
      'contentId': contentId,
      'contentType': contentType,
      'mediaUrl': mediaUrl,
      'thumbnailUrl': thumbnailUrl,
      'category': category.toString().split('.').last,
      'tags': tags,
      'caption': caption,
      'originalDate': Timestamp.fromDate(originalDate),
      'savedAt': Timestamp.fromDate(savedAt),
      'isFavorite': isFavorite,
      'location': location,
      'peopleTagged': peopleTagged,
    };
  }
}

/// Flashback Model
class Flashback {
  final String id;
  final String userId;
  final String title;
  final String description;
  final DateTime flashbackDate; // Date being remembered
  final List<String> memoryIds;
  final String? coverImageUrl;
  final DateTime createdAt;
  final bool isAutoGenerated;

  Flashback({
    required this.id,
    required this.userId,
    required this.title,
    required this.description,
    required this.flashbackDate,
    required this.memoryIds,
    this.coverImageUrl,
    required this.createdAt,
    this.isAutoGenerated = false,
  });

  factory Flashback.fromMap(Map<String, dynamic> map, String id) {
    return Flashback(
      id: id,
      userId: map['userId'] ?? '',
      title: map['title'] ?? '',
      description: map['description'] ?? '',
      flashbackDate: (map['flashbackDate'] as Timestamp).toDate(),
      memoryIds: List<String>.from(map['memoryIds'] ?? []),
      coverImageUrl: map['coverImageUrl'],
      createdAt: (map['createdAt'] as Timestamp).toDate(),
      isAutoGenerated: map['isAutoGenerated'] ?? false,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'userId': userId,
      'title': title,
      'description': description,
      'flashbackDate': Timestamp.fromDate(flashbackDate),
      'memoryIds': memoryIds,
      'coverImageUrl': coverImageUrl,
      'createdAt': Timestamp.fromDate(createdAt),
      'isAutoGenerated': isAutoGenerated,
    };
  }
}

/// Memories & Flashbacks Service
/// Snapchat-style memories system with automatic flashback generation
class MemoriesFlashbacksService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseStorage _storage = FirebaseStorage.instance;
  final AuthService _authService = AuthService();

  /// Save content to memories
  Future<Memory> saveToMemories({
    required String contentId,
    required String contentType,
    required String mediaUrl,
    String? thumbnailUrl,
    MemoryCategory category = MemoryCategory.other,
    List<String>? tags,
    String? caption,
    DateTime? originalDate,
    Map<String, dynamic>? location,
    List<String>? peopleTagged,
  }) async {
    try {
      final user = _authService.currentUser;
      if (user == null) throw Exception('User not authenticated');

      final String memoryId = _firestore.collection('memories').doc().id;

      final memory = Memory(
        id: memoryId,
        userId: user.uid,
        contentId: contentId,
        contentType: contentType,
        mediaUrl: mediaUrl,
        thumbnailUrl: thumbnailUrl,
        category: category,
        tags: tags ?? [],
        caption: caption,
        originalDate: originalDate ?? DateTime.now(),
        savedAt: DateTime.now(),
        isFavorite: false,
        location: location,
        peopleTagged: peopleTagged,
      );

      await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('memories')
          .doc(memoryId)
          .set(memory.toMap());

      return memory;
    } catch (e) {
      print('Error saving to memories: $e');
      rethrow;
    }
  }

  /// Get all memories
  Future<List<Memory>> getAllMemories({
    int limit = 100,
    DateTime? startDate,
    DateTime? endDate,
  }) async {
    try {
      final user = _authService.currentUser;
      if (user == null) throw Exception('User not authenticated');

      var query = _firestore
          .collection('users')
          .doc(user.uid)
          .collection('memories')
          .orderBy('originalDate', descending: true);

      if (startDate != null) {
        query = query.where('originalDate',
            isGreaterThanOrEqualTo: Timestamp.fromDate(startDate));
      }

      if (endDate != null) {
        query = query.where('originalDate',
            isLessThanOrEqualTo: Timestamp.fromDate(endDate));
      }

      final querySnapshot = await query.limit(limit).get();

      return querySnapshot.docs
          .map((doc) => Memory.fromMap(doc.data(), doc.id))
          .toList();
    } catch (e) {
      print('Error getting memories: $e');
      return [];
    }
  }

  /// Get memories by category
  Future<List<Memory>> getMemoriesByCategory(
    MemoryCategory category, {
    int limit = 50,
  }) async {
    try {
      final user = _authService.currentUser;
      if (user == null) throw Exception('User not authenticated');

      final querySnapshot = await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('memories')
          .where('category', isEqualTo: category.toString().split('.').last)
          .orderBy('originalDate', descending: true)
          .limit(limit)
          .get();

      return querySnapshot.docs
          .map((doc) => Memory.fromMap(doc.data(), doc.id))
          .toList();
    } catch (e) {
      print('Error getting memories by category: $e');
      return [];
    }
  }

  /// Search memories
  Future<List<Memory>> searchMemories(String query) async {
    try {
      final user = _authService.currentUser;
      if (user == null) throw Exception('User not authenticated');

      if (query.isEmpty) return getAllMemories(limit: 50);

      // Search in tags and caption
      final querySnapshot = await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('memories')
          .where('tags', arrayContains: query.toLowerCase())
          .limit(50)
          .get();

      return querySnapshot.docs
          .map((doc) => Memory.fromMap(doc.data(), doc.id))
          .toList();
    } catch (e) {
      print('Error searching memories: $e');
      return [];
    }
  }

  /// Get favorite memories
  Future<List<Memory>> getFavoriteMemories({int limit = 50}) async {
    try {
      final user = _authService.currentUser;
      if (user == null) throw Exception('User not authenticated');

      final querySnapshot = await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('memories')
          .where('isFavorite', isEqualTo: true)
          .orderBy('originalDate', descending: true)
          .limit(limit)
          .get();

      return querySnapshot.docs
          .map((doc) => Memory.fromMap(doc.data(), doc.id))
          .toList();
    } catch (e) {
      print('Error getting favorite memories: $e');
      return [];
    }
  }

  /// Toggle memory favorite status
  Future<void> toggleFavorite(String memoryId, bool isFavorite) async {
    try {
      final user = _authService.currentUser;
      if (user == null) throw Exception('User not authenticated');

      await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('memories')
          .doc(memoryId)
          .update({'isFavorite': isFavorite});
    } catch (e) {
      print('Error toggling favorite: $e');
      rethrow;
    }
  }

  /// Delete memory
  Future<void> deleteMemory(String memoryId) async {
    try {
      final user = _authService.currentUser;
      if (user == null) throw Exception('User not authenticated');

      await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('memories')
          .doc(memoryId)
          .delete();
    } catch (e) {
      print('Error deleting memory: $e');
      rethrow;
    }
  }

  /// Generate automatic flashback for a specific date
  Future<Flashback?> generateFlashback(DateTime date) async {
    try {
      final user = _authService.currentUser;
      if (user == null) throw Exception('User not authenticated');

      // Get memories from the same day in previous years
      final memories = await _getMemoriesForDate(date);

      if (memories.isEmpty) return null;

      // Generate flashback title and description
      final yearsAgo = DateTime.now().year - date.year;
      final title =
          yearsAgo == 1 ? 'One Year Ago Today' : '$yearsAgo Years Ago Today';

      final description = _generateFlashbackDescription(memories, date);

      // Create flashback
      final flashbackId = _firestore.collection('flashbacks').doc().id;

      final flashback = Flashback(
        id: flashbackId,
        userId: user.uid,
        title: title,
        description: description,
        flashbackDate: date,
        memoryIds: memories.map((m) => m.id).toList(),
        coverImageUrl: memories.first.thumbnailUrl ?? memories.first.mediaUrl,
        createdAt: DateTime.now(),
        isAutoGenerated: true,
      );

      await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('flashbacks')
          .doc(flashbackId)
          .set(flashback.toMap());

      return flashback;
    } catch (e) {
      print('Error generating flashback: $e');
      return null;
    }
  }

  /// Get today's flashbacks (memories from previous years on this date)
  Future<List<Flashback>> getTodaysFlashbacks() async {
    try {
      final today = DateTime.now();
      final flashbacks = <Flashback>[];

      // Check flashbacks from 1 to 10 years ago
      for (int yearsAgo = 1; yearsAgo <= 10; yearsAgo++) {
        final flashbackDate = DateTime(
          today.year - yearsAgo,
          today.month,
          today.day,
        );

        final flashback = await generateFlashback(flashbackDate);
        if (flashback != null) {
          flashbacks.add(flashback);
        }
      }

      return flashbacks;
    } catch (e) {
      print('Error getting today\'s flashbacks: $e');
      return [];
    }
  }

  /// Get all flashbacks
  Future<List<Flashback>> getAllFlashbacks({int limit = 50}) async {
    try {
      final user = _authService.currentUser;
      if (user == null) throw Exception('User not authenticated');

      final querySnapshot = await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('flashbacks')
          .orderBy('createdAt', descending: true)
          .limit(limit)
          .get();

      return querySnapshot.docs
          .map((doc) => Flashback.fromMap(doc.data(), doc.id))
          .toList();
    } catch (e) {
      print('Error getting flashbacks: $e');
      return [];
    }
  }

  /// Get memories for flashback
  Future<List<Memory>> getFlashbackMemories(String flashbackId) async {
    try {
      final user = _authService.currentUser;
      if (user == null) throw Exception('User not authenticated');

      final flashbackDoc = await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('flashbacks')
          .doc(flashbackId)
          .get();

      if (!flashbackDoc.exists) return [];

      final flashbackData = flashbackDoc.data()!;
      final memoryIds = List<String>.from(flashbackData['memoryIds'] ?? []);

      final memories = <Memory>[];
      for (String memoryId in memoryIds) {
        final memoryDoc = await _firestore
            .collection('users')
            .doc(user.uid)
            .collection('memories')
            .doc(memoryId)
            .get();

        if (memoryDoc.exists) {
          memories.add(Memory.fromMap(memoryDoc.data()!, memoryDoc.id));
        }
      }

      return memories;
    } catch (e) {
      print('Error getting flashback memories: $e');
      return [];
    }
  }

  /// Create story from memories
  Future<String> createStoryFromMemories(List<String> memoryIds) async {
    try {
      final user = _authService.currentUser;
      if (user == null) throw Exception('User not authenticated');

      if (memoryIds.isEmpty) {
        throw Exception('No memories selected');
      }

      // Get memories
      final memories = <Memory>[];
      for (String memoryId in memoryIds) {
        final memoryDoc = await _firestore
            .collection('users')
            .doc(user.uid)
            .collection('memories')
            .doc(memoryId)
            .get();

        if (memoryDoc.exists) {
          memories.add(Memory.fromMap(memoryDoc.data()!, memoryDoc.id));
        }
      }

      if (memories.isEmpty) {
        throw Exception('No valid memories found');
      }

      // Create story with memories collage/slideshow
      final storyId = _firestore.collection('stories').doc().id;

      await _firestore.collection('stories').doc(storyId).set({
        'id': storyId,
        'userId': user.uid,
        'username': user.displayName ?? 'Unknown',
        'userProfileImage': user.photoURL ?? '',
        'type': 'memory',
        'memoryIds': memoryIds,
        'mediaUrl': memories.first.mediaUrl,
        'thumbnailUrl': memories.first.thumbnailUrl ?? memories.first.mediaUrl,
        'caption': 'Memory Story',
        'createdAt': FieldValue.serverTimestamp(),
        'expiresAt': Timestamp.fromDate(
          DateTime.now().add(const Duration(hours: 24)),
        ),
        'views': 0,
        'status': 'active',
      });

      return storyId;
    } catch (e) {
      print('Error creating story from memories: $e');
      rethrow;
    }
  }

  /// Update memory category
  Future<void> updateMemoryCategory(
    String memoryId,
    MemoryCategory category,
  ) async {
    try {
      final user = _authService.currentUser;
      if (user == null) throw Exception('User not authenticated');

      await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('memories')
          .doc(memoryId)
          .update({
        'category': category.toString().split('.').last,
      });
    } catch (e) {
      print('Error updating memory category: $e');
      rethrow;
    }
  }

  /// Add tags to memory
  Future<void> addTagsToMemory(String memoryId, List<String> tags) async {
    try {
      final user = _authService.currentUser;
      if (user == null) throw Exception('User not authenticated');

      await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('memories')
          .doc(memoryId)
          .update({
        'tags':
            FieldValue.arrayUnion(tags.map((t) => t.toLowerCase()).toList()),
      });
    } catch (e) {
      print('Error adding tags: $e');
      rethrow;
    }
  }

  /// Helper: Get memories for specific date
  Future<List<Memory>> _getMemoriesForDate(DateTime date) async {
    try {
      final user = _authService.currentUser;
      if (user == null) return [];

      final startOfDay = DateTime(date.year, date.month, date.day);
      final endOfDay = startOfDay.add(const Duration(days: 1));

      final querySnapshot = await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('memories')
          .where('originalDate',
              isGreaterThanOrEqualTo: Timestamp.fromDate(startOfDay))
          .where('originalDate', isLessThan: Timestamp.fromDate(endOfDay))
          .get();

      return querySnapshot.docs
          .map((doc) => Memory.fromMap(doc.data(), doc.id))
          .toList();
    } catch (e) {
      print('Error getting memories for date: $e');
      return [];
    }
  }

  /// Helper: Generate flashback description
  String _generateFlashbackDescription(List<Memory> memories, DateTime date) {
    final count = memories.length;
    final yearsAgo = DateTime.now().year - date.year;

    if (count == 1) {
      return 'You shared a moment $yearsAgo ${yearsAgo == 1 ? "year" : "years"} ago';
    } else {
      return 'You shared $count moments $yearsAgo ${yearsAgo == 1 ? "year" : "years"} ago';
    }
  }

  /// Get all categories
  List<MemoryCategory> getAllCategories() {
    return MemoryCategory.values;
  }
}
