// Generated by Wrangler by running `wrangler types`

interface Env {
	STRIPE_SECRET_KEY: "";
	STRIPE_WEBHOOK_SECRET: "";
	AGORA_APP_ID: "";
	AGORA_APP_CERTIFICATE: "";
	CHAT_APP_KEY: "";
	CHAT_CLIENT_ID: "";
	CHAT_CLIENT_SECRET: "";
	CLOUDFLARE_STREAM_ACCOUNT_ID: "b62ed7e1cf0e1dc886f363573bad4bdb";
	CLOUDFLARE_STREAM_API_TOKEN: "";
	R2_BUCKET: "";
	KV_CACHE: "";
	D1_DB: "";
	QUEUE_EVENTS: "";
}
