// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxG4sI_RO6IN8kItCTeXJkFb9zFeEnQ_M',
    appId: '1:603021639103:web:c18ace07125da11a5ab50a',
    messagingSenderId: '603021639103',
    projectId: 'spaktok-e7866',
    authDomain: 'spaktok-e7866.firebaseapp.com',
    storageBucket: 'spaktok-e7866.firebasestorage.app',
    measurementId: 'G-1DTF6R1ZBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqdbdI6MI7mBdV0cu1oqw98vybIMczF1M',
    appId: '1:603021639103:android:3423fed07bbea9825ab50a',
    messagingSenderId: '603021639103',
    projectId: 'spaktok-e7866',
    storageBucket: 'spaktok-e7866.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYMXwdpXPOYqby7aEUq6-yIGdSt7jAz_c',
    appId: '1:603021639103:ios:5d66dae17f8f1cc55ab50a',
    messagingSenderId: '603021639103',
    projectId: 'spaktok-e7866',
    storageBucket: 'spaktok-e7866.firebasestorage.app',
    iosBundleId: 'com.spaktok.platform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYMXwdpXPOYqby7aEUq6-yIGdSt7jAz_c',
    appId: '1:603021639103:ios:48f59ca3f60b59435ab50a',
    messagingSenderId: '603021639103',
    projectId: 'spaktok-e7866',
    storageBucket: 'spaktok-e7866.firebasestorage.app',
    iosBundleId: 'com.spaktok.desktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxG4sI_RO6IN8kItCTeXJkFb9zFeEnQ_M',
    appId: '1:603021639103:web:5f39bf723c3d33365ab50a',
    messagingSenderId: '603021639103',
    projectId: 'spaktok-e7866',
    authDomain: 'spaktok-e7866.firebaseapp.com',
    storageBucket: 'spaktok-e7866.firebasestorage.app',
    measurementId: 'G-GYLXK1H2VF',
  );
}
