type User @table {
  username: String!
  email: String!
  passwordHash: String!
  createdAt: Timestamp!
  displayName: String
  bio: String
  profilePictureUrl: String
  lastLoginAt: Timestamp
}

type Post @table {
  author: User
  content: String!
  createdAt: Timestamp!
  imageUrl: String
  videoUrl: String
}

type Comment @table {
  author: User
  post: Post
  text: String!
  createdAt: Timestamp!
}

type Like @table {
  user: User
  post: Post
  createdAt: Timestamp!
}

type Follow @table(key: ["follower", "followed"]) {
  follower: User!
  followed: User!
  createdAt: Timestamp!
}

type Group @table {
  admin: User
  name: String!
  createdAt: Timestamp!
  description: String
  groupPictureUrl: String
}

type GroupMembership @table(key: ["user", "group"]) {
  user: User!
  group: Group!
  joinedAt: Timestamp!
}
