name: Spaktok CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run every hour to check for updates
    - cron: '0 * * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Verify Flutter installation
      run: flutter doctor -v
      
    - name: Check for missing files
      run: |
        echo "Checking for essential files..."
        files=(
          "pubspec.yaml"
          "lib/main.dart"
          "web/index.html"
          "firebase.json"
          "android/app/build.gradle"
          "ios/Runner/Info.plist"
        )
        for file in "${files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "Warning: $file is missing!"
          else
            echo "✓ $file exists"
          fi
        done
        
    - name: Check Firebase configuration
      run: |
        if [ ! -f "lib/firebase_options.dart" ]; then
          echo "Warning: firebase_options.dart is missing!"
          echo "Please run 'flutterfire configure' to generate it."
        else
          echo "✓ Firebase configuration exists"
        fi
        
    - name: Analyze code
      run: flutter analyze
      continue-on-error: true
      
    - name: Run tests
      run: flutter test
      continue-on-error: true
      
    - name: Build Android APK
      run: flutter build apk --release
      continue-on-error: true
      
    - name: Build Web
      run: flutter build web --release
      continue-on-error: true
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: spaktok-builds
        path: |
          build/app/outputs/flutter-apk/
          build/web/
        retention-days: 30
        
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Check for outdated dependencies
      run: flutter pub outdated
      continue-on-error: true
      
    - name: Update dependencies
      run: flutter pub upgrade
      continue-on-error: true
      
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Run security scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
      continue-on-error: true
      
    - name: Upload scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
      continue-on-error: true
