name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'

      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: frontend

      - name: Analyze Flutter code
        run: flutter analyze
        working-directory: frontend

      - name: Run Flutter tests
        run: flutter test
        working-directory: frontend

      - name: Build Flutter Web
        run: flutter build web --release
        working-directory: frontend

  build_and_test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Lint backend (placeholder)
        run: echo "No backend linters configured yet."
        working-directory: backend

  firebase_deploy:
    runs-on: ubuntu-latest
    needs: [build_and_test_frontend, build_and_test_backend]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPAKTOK_E7866 }}'
          projectId: spaktok-e7866
          channelId: live
          target: spaktok
