name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      # إلغاء أي Proxy على بيئة الـ runner (تحسباً)
      - name: Clear proxies on runner
        shell: bash
        run: |
          git config --global --unset http.proxy || true
          git config --global --unset https.proxy || true
          unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY no_proxy NO_PROXY || true
          echo "Proxies cleared on runner."

      - name: Setup Flutter
        uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@e2eda2e106cfa35cdbcf4ac9ddaf6c4756df2c8c
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPAKTOK_E7866 }}'
          channelId: live
          projectId: spaktok-e7866
